### ISSUE TITLE
Add Partnered logo to website.

### ISSUE THREAD

**Issue by ThomasShaped** [gaymers-discord/gaymers-website#10]
Add the partnered logo to the website.

@brandon-a would appreciate if you could upload the files here so I don't have to hunt them down later, and maybe github won't mess with the transparency.

**Comment by brandon-a** [comment]
Here are the two images, let me know if you have any issues.

![discord_partner_day](https://cloud.githubusercontent.com/assets/10055919/26705181/4c51a67a-46e9-11e7-93c9-b9f7a741c8c6.png)
![discord_partner_night](https://cloud.githubusercontent.com/assets/10055919/26705184/4e884610-46e9-11e7-8f78-3b03eef12bf5.png)
